[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "Agave Nerd Font Mono"

[font.bold_italic]
family = "Agave Nerd Font Mono"

[font.italic]
family = "Agave Nerd Font Mono"

[font.normal]
family = "Agave Nerd Font Mono"

[shell]
program = "/usr/bin/zsh"

[window]
dynamic_title = false
opacity = 1.0
